learning_rate: 0.001
batch_size: 32
num_epochs: 10
path_to_initial_weights: resnet18/weights_0.pth
path_to_result_weights: resnet18/weights_1.pth
dataset_idx: 1

# for 2nd dataset use this:
# learning_rate: 0.001
# batch_size: 32
# num_epochs: 10
# path_to_initial_weights: resnet18/weights_1.pth
# path_to_result_weights: resnet18/weights_2.pth
# dataset_idx: 2
